name: re_conver
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  rive: ^0.13.20
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  timeago: ^3.7.1
  flutter_image_compress: ^2.4.0
  foundation: ^0.0.5
  timeline_tile: ^2.0.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  flutter_dotenv: ^5.2.1
  google_places_flutter: ^2.1.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  google_fonts: ^6.3.0
  googleapis_auth: ^2.0.0
  shared_preferences: ^2.5.3
  google_places_autocomplete_text_field: ^1.1.0
  country_picker: ^2.0.27
  firebase_messaging: ^16.0.0
  speech_to_text: ^7.3.0
  sqflite: ^2.4.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  record: ^6.1.1
  audioplayers: ^6.5.0
  permission_handler: ^12.0.1
  flutter_slidable: ^4.0.1
  cached_network_image: ^3.4.1
  gallery_saver_plus: ^3.2.9
  device_info_plus: ^12.1.0
  carousel_slider: ^5.1.1
  change_app_package_name: ^1.5.0
  share_plus: ^12.0.0
  geoflutterfire_plus: ^0.0.33
  geocoding: ^4.0.0
  google_nav_bar: ^5.0.7
  animated_bottom_navigation_bar: ^1.4.0
  curved_navigation_bar: ^1.0.6
  flutter_svg: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: default
      fonts:
        - asset: assets/default.ttf
    - family: login
      fonts:
        - asset: assets/login.ttf
    - family: fancy
      fonts:
        - asset: assets/fancy2.ttf
