// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGLGC1eWoS5i-qHDjw18IWLTnopfbXRA',
    appId: '1:1049878222012:android:7a6a3a4610f4602eacecb9',
    messagingSenderId: '1049878222012',
    projectId: 'whatsappclone-5ad8f',
    storageBucket: 'whatsappclone-5ad8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABNm9h2sbwA4e86yuvcEmuzHI5Ny65GWU',
    appId: '1:1049878222012:ios:447c6f3fdf01f715acecb9',
    messagingSenderId: '1049878222012',
    projectId: 'whatsappclone-5ad8f',
    storageBucket: 'whatsappclone-5ad8f.firebasestorage.app',
    iosBundleId: 'com.example.reConver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCCxQ0AYTHy6A6DrfW7ylYxjGW6AZA1OQ',
    appId: '1:1049878222012:web:54584a8098728e70acecb9',
    messagingSenderId: '1049878222012',
    projectId: 'whatsappclone-5ad8f',
    authDomain: 'whatsappclone-5ad8f.firebaseapp.com',
    storageBucket: 'whatsappclone-5ad8f.firebasestorage.app',
    measurementId: 'G-EQ99QMVB2Y',
  );

}