name: shared_data
description: repo for shared data
environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.5.3
  firebase_auth: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter